/**
 * ヒアリングシート生成システム
 * テンプレートからPDF/Markdown/Google Form形式で出力
 */

import { GoogleGenAI } from "@google/genai";
import { getDefaultTextModel } from "@/lib/ai/models";
import {
  LP_HEARING_TEMPLATE,
  type HearingSheetTemplate,
  type HearingQuestion,
  type HearingSection,
} from "./templates/lp-hearing";

// ============================================
// 型定義
// ============================================

export interface HearingResponse {
  questionId: string;
  value: string | string[];
}

export interface GeneratedHearingSheet {
  templateId: string;
  responses: HearingResponse[];
  createdAt: string;
  projectName?: string;
}

export interface HearingSheetExport {
  format: "markdown" | "html" | "json" | "notion";
  content: string;
  filename: string;
}

export interface N1InsightAnalysis {
  persona: {
    name: string;
    summary: string;
    situation: string;
    painPoints: string[];
    desires: string[];
    fears: string[];
    objections: string[];
  };
  copywritingAngle: {
    headline: string;
    subheadline: string;
    emotionalHooks: string[];
    keyMessages: string[];
  };
  recommendedStructure: string[];
}

// ============================================
// エクスポート関数
// ============================================

/**
 * Markdown形式でエクスポート
 */
export function exportToMarkdown(
  template: HearingSheetTemplate,
  responses: HearingResponse[] = []
): HearingSheetExport {
  const responseMap = new Map(responses.map((r) => [r.questionId, r.value]));
  const projectName = responseMap.get("project_name") || "unnamed";

  let content = `# ${template.name}\n\n`;
  content += `> ${template.description}\n\n`;
  content += `---\n\n`;

  for (const section of template.sections) {
    content += `## ${section.icon} ${section.title}\n\n`;
    content += `*${section.description}*\n\n`;

    for (const question of section.questions) {
      const value = responseMap.get(question.id);
      const displayValue = Array.isArray(value) ? value.join(", ") : value || "（未回答）";
      const requiredMark = question.required ? " *" : "";
      const n1Mark = question.n1Related ? " ⭐" : "";

      content += `### ${question.question}${requiredMark}${n1Mark}\n\n`;
      if (question.description) {
        content += `> ${question.description}\n\n`;
      }
      content += `${displayValue}\n\n`;
    }
  }

  content += `---\n\n`;
  content += `*Generated by LP Builder Pro - ${new Date().toISOString()}*\n`;

  return {
    format: "markdown",
    content,
    filename: `hearing-sheet-${projectName}-${Date.now()}.md`,
  };
}

/**
 * HTML形式でエクスポート（印刷用）
 */
export function exportToHtml(
  template: HearingSheetTemplate,
  responses: HearingResponse[]
): HearingSheetExport {
  const responseMap = new Map(responses.map((r) => [r.questionId, r.value]));
  const projectName = responseMap.get("project_name") || "unnamed";

  let content = `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${template.name}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Hiragino Sans', 'Meiryo', sans-serif; line-height: 1.6; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 24px; margin-bottom: 10px; color: #333; }
    h2 { font-size: 18px; margin: 30px 0 15px; padding-bottom: 8px; border-bottom: 2px solid #333; color: #333; }
    h3 { font-size: 14px; margin: 20px 0 8px; color: #555; }
    .section { margin-bottom: 30px; }
    .question { margin-bottom: 20px; padding: 15px; background: #f9f9f9; border-radius: 8px; }
    .question.n1 { background: #fff8e6; border-left: 4px solid #f5a623; }
    .question.required h3::after { content: " *"; color: #e53935; }
    .description { font-size: 12px; color: #666; margin-bottom: 8px; }
    .answer { font-size: 14px; white-space: pre-wrap; }
    .empty { color: #999; font-style: italic; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>${template.name}</h1>
  <p style="color: #666; margin-bottom: 30px;">${template.description}</p>
`;

  for (const section of template.sections) {
    content += `  <div class="section">
    <h2>${section.icon} ${section.title}</h2>
    <p style="color: #666; font-size: 14px; margin-bottom: 15px;">${section.description}</p>
`;

    for (const question of section.questions) {
      const value = responseMap.get(question.id);
      const displayValue = Array.isArray(value) ? value.join(", ") : value || "";
      const classes = [
        "question",
        question.required ? "required" : "",
        question.n1Related ? "n1" : "",
      ].filter(Boolean).join(" ");

      content += `    <div class="${classes}">
      <h3>${question.question}</h3>
`;
      if (question.description) {
        content += `      <p class="description">${question.description}</p>\n`;
      }
      content += `      <p class="answer${!displayValue ? " empty" : ""}">${displayValue || "（未回答）"}</p>
    </div>
`;
    }
    content += `  </div>\n`;
  }

  content += `  <div class="footer">
    Generated by LP Builder Pro - ${new Date().toISOString()}
  </div>
</body>
</html>`;

  return {
    format: "html",
    content,
    filename: `hearing-sheet-${projectName}-${Date.now()}.html`,
  };
}

/**
 * JSON形式でエクスポート
 */
export function exportToJson(
  template: HearingSheetTemplate,
  responses: HearingResponse[]
): HearingSheetExport {
  const responseMap = new Map(responses.map((r) => [r.questionId, r.value]));
  const projectName = responseMap.get("project_name") || "unnamed";

  const data: GeneratedHearingSheet = {
    templateId: template.id,
    responses,
    createdAt: new Date().toISOString(),
    projectName: String(projectName),
  };

  return {
    format: "json",
    content: JSON.stringify(data, null, 2),
    filename: `hearing-sheet-${projectName}-${Date.now()}.json`,
  };
}

/**
 * Notion形式でエクスポート（コピペ用Markdown）
 */
export function exportToNotion(
  template: HearingSheetTemplate,
  responses: HearingResponse[]
): HearingSheetExport {
  const responseMap = new Map(responses.map((r) => [r.questionId, r.value]));
  const projectName = responseMap.get("project_name") || "unnamed";

  let content = `# ${template.name}\n\n`;

  for (const section of template.sections) {
    content += `## ${section.icon} ${section.title}\n\n`;

    for (const question of section.questions) {
      const value = responseMap.get(question.id);
      const displayValue = Array.isArray(value) ? value.join(", ") : value || "—";
      const n1Badge = question.n1Related ? " `N1`" : "";

      content += `**${question.question}**${n1Badge}\n`;
      content += `${displayValue}\n\n`;
    }
  }

  return {
    format: "notion",
    content,
    filename: `hearing-sheet-${projectName}-notion.md`,
  };
}

// ============================================
// AI分析機能
// ============================================

/**
 * N1顧客インサイトをAIで分析
 */
export async function analyzeN1Insights(
  responses: HearingResponse[]
): Promise<N1InsightAnalysis | null> {
  try {
    const responseMap = new Map(responses.map((r) => [r.questionId, r.value]));

    // N1関連の回答を抽出
    const n1Data = {
      name: responseMap.get("n1_name") || "",
      situation: responseMap.get("n1_situation") || "",
      pain: responseMap.get("n1_pain") || "",
      desire: responseMap.get("n1_desire") || "",
      fear: responseMap.get("n1_fear") || "",
      tried: responseMap.get("n1_tried") || "",
      objection: responseMap.get("n1_objection") || "",
      trigger: responseMap.get("n1_trigger") || "",
      benefits: responseMap.get("product_benefits") || "",
      usp: responseMap.get("product_usp") || "",
    };

    const ai = new GoogleGenAI({});
    const model = getDefaultTextModel();

    const prompt = `あなたは一流のマーケティングストラテジストです。
以下のヒアリング回答を分析し、N1顧客インサイトとLP制作に活用できる情報を抽出してください。

## ヒアリング回答

### N1顧客名
${n1Data.name}

### 現在の状況
${n1Data.situation}

### 最も深刻な悩み
${n1Data.pain}

### 本当に望んでいること
${n1Data.desire}

### 最も恐れていること
${n1Data.fear}

### これまで試したこと
${n1Data.tried}

### 購入をためらう理由
${n1Data.objection}

### 購入の決め手
${n1Data.trigger}

### 商品のベネフィット
${n1Data.benefits}

### 独自の強み（USP）
${n1Data.usp}

## 出力形式（JSON）
{
  "persona": {
    "name": "N1顧客の名前",
    "summary": "1文でペルソナを要約",
    "situation": "状況の要約",
    "painPoints": ["痛みポイント1", "痛みポイント2", "痛みポイント3"],
    "desires": ["願望1", "願望2", "願望3"],
    "fears": ["恐怖1", "恐怖2"],
    "objections": ["反論1", "反論2"]
  },
  "copywritingAngle": {
    "headline": "推奨ヘッドライン案",
    "subheadline": "推奨サブヘッドライン案",
    "emotionalHooks": ["感情フック1", "感情フック2", "感情フック3"],
    "keyMessages": ["キーメッセージ1", "キーメッセージ2", "キーメッセージ3"]
  },
  "recommendedStructure": ["LPセクション1", "LPセクション2", "LPセクション3"]
}`;

    const response = await ai.models.generateContent({
      model,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      },
    });

    const text = response.text || "";
    return JSON.parse(text) as N1InsightAnalysis;
  } catch (error) {
    console.error("[HearingSheetGenerator] N1 analysis error:", error);
    return null;
  }
}

// ============================================
// ヘルパー関数
// ============================================

/**
 * デフォルトテンプレートを取得
 */
export function getDefaultTemplate(): HearingSheetTemplate {
  return LP_HEARING_TEMPLATE;
}

/**
 * LPヒアリングテンプレートを取得（エイリアス）
 */
export function getLPHearingTemplate(): HearingSheetTemplate {
  return LP_HEARING_TEMPLATE;
}

/**
 * HTML形式でエクスポート（エイリアス - 大文字版）
 */
export function exportToHTML(
  template: HearingSheetTemplate,
  responses?: HearingResponse[],
  options?: { editable?: boolean }
): string {
  if (!responses || responses.length === 0) {
    // 空のフォーム用HTML生成
    return generateEditableHTML(template, options?.editable ?? false);
  }
  return exportToHtml(template, responses).content;
}

/**
 * 編集可能なHTMLフォームを生成
 */
function generateEditableHTML(template: HearingSheetTemplate, editable: boolean): string {
  let content = `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${template.name}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Hiragino Sans', 'Meiryo', sans-serif; line-height: 1.6; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 24px; margin-bottom: 10px; color: #333; }
    h2 { font-size: 18px; margin: 30px 0 15px; padding-bottom: 8px; border-bottom: 2px solid #333; color: #333; }
    .section { margin-bottom: 30px; }
    .question { margin-bottom: 20px; padding: 15px; background: #f9f9f9; border-radius: 8px; }
    .question.n1 { background: #fff8e6; border-left: 4px solid #f5a623; }
    .question.required label::after { content: " *"; color: #e53935; }
    .description { font-size: 12px; color: #666; margin-bottom: 8px; }
    input, textarea, select { width: 100%; padding: 10px; border: 1px solid #ddd; border-radius: 4px; font-size: 14px; }
    textarea { min-height: 80px; resize: vertical; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }
  </style>
</head>
<body>
  <h1>${template.name}</h1>
  <p style="color: #666; margin-bottom: 30px;">${template.description}</p>
`;

  for (const section of template.sections) {
    content += `  <div class="section">
    <h2>${section.icon} ${section.title}</h2>
    <p style="color: #666; font-size: 14px; margin-bottom: 15px;">${section.description}</p>
`;

    for (const question of section.questions) {
      const classes = [
        "question",
        question.required ? "required" : "",
        question.n1Related ? "n1" : "",
      ].filter(Boolean).join(" ");

      content += `    <div class="${classes}">
      <label>${question.question}</label>
`;
      if (question.description) {
        content += `      <p class="description">${question.description}</p>\n`;
      }

      if (editable) {
        switch (question.type) {
          case "textarea":
            content += `      <textarea name="${question.id}" placeholder="${question.placeholder || ""}"></textarea>\n`;
            break;
          case "select":
            content += `      <select name="${question.id}">
        <option value="">選択してください</option>
        ${question.options?.map((o) => `<option value="${o}">${o}</option>`).join("\n        ") || ""}
      </select>\n`;
            break;
          default:
            content += `      <input type="text" name="${question.id}" placeholder="${question.placeholder || ""}" />\n`;
        }
      } else {
        content += `      <p>（記入欄）</p>\n`;
      }

      content += `    </div>
`;
    }
    content += `  </div>
`;
  }

  content += `  <div class="footer">
    Generated by LP Builder Pro - ${new Date().toISOString()}
  </div>
</body>
</html>`;

  return content;
}

/**
 * Google Form用JSONを生成
 */
export function exportToGoogleFormJSON(template: HearingSheetTemplate): string {
  const formData = {
    title: template.name,
    description: template.description,
    sections: template.sections.map((section) => ({
      title: `${section.icon} ${section.title}`,
      description: section.description,
      questions: section.questions.map((q) => ({
        id: q.id,
        title: q.question,
        description: q.description || "",
        type: q.type === "textarea" ? "PARAGRAPH_TEXT" :
              q.type === "select" ? "MULTIPLE_CHOICE" :
              q.type === "multiselect" ? "CHECKBOX" : "SHORT_ANSWER",
        required: q.required,
        options: q.options || [],
      })),
    })),
  };

  return JSON.stringify(formData, null, 2);
}

/**
 * N1関連データを抽出
 */
export function extractN1Data(responses: HearingResponse[]): Record<string, string | string[]> {
  const responseMap = new Map(responses.map((r) => [r.questionId, r.value]));
  const n1Questions = LP_HEARING_TEMPLATE.sections.flatMap((s) =>
    s.questions.filter((q) => q.n1Related)
  );

  const n1Data: Record<string, string | string[]> = {};
  for (const q of n1Questions) {
    const value = responseMap.get(q.id);
    if (value) {
      n1Data[q.id] = value;
    }
  }

  return n1Data;
}

/**
 * チェックリストを生成
 */
export function generateChecklist(template: HearingSheetTemplate): {
  sections: {
    title: string;
    items: { id: string; label: string; required: boolean; n1Related: boolean }[];
  }[];
  totalItems: number;
  requiredItems: number;
  n1Items: number;
} {
  let totalItems = 0;
  let requiredItems = 0;
  let n1Items = 0;

  const sections = template.sections.map((section) => ({
    title: `${section.icon} ${section.title}`,
    items: section.questions.map((q) => {
      totalItems++;
      if (q.required) requiredItems++;
      if (q.n1Related) n1Items++;
      return {
        id: q.id,
        label: q.question,
        required: q.required,
        n1Related: q.n1Related,
      };
    }),
  }));

  return { sections, totalItems, requiredItems, n1Items };
}

/**
 * セクション一覧を取得
 */
export function getSections(): HearingSection[] {
  return LP_HEARING_TEMPLATE.sections;
}

/**
 * 質問を取得
 */
export function getQuestion(questionId: string): HearingQuestion | undefined {
  for (const section of LP_HEARING_TEMPLATE.sections) {
    const question = section.questions.find((q) => q.id === questionId);
    if (question) return question;
  }
  return undefined;
}

/**
 * 必須質問の回答状況をチェック
 */
export function validateRequiredResponses(
  responses: HearingResponse[]
): { valid: boolean; missingQuestions: string[] } {
  const responseMap = new Map(responses.map((r) => [r.questionId, r.value]));
  const missingQuestions: string[] = [];

  for (const section of LP_HEARING_TEMPLATE.sections) {
    for (const question of section.questions) {
      if (question.required) {
        const value = responseMap.get(question.id);
        if (!value || (Array.isArray(value) && value.length === 0)) {
          missingQuestions.push(question.question);
        }
      }
    }
  }

  return {
    valid: missingQuestions.length === 0,
    missingQuestions,
  };
}

/**
 * 回答の完成度を計算
 */
export function calculateCompleteness(responses: HearingResponse[]): {
  total: number;
  answered: number;
  percentage: number;
  n1Percentage: number;
} {
  const responseMap = new Map(responses.map((r) => [r.questionId, r.value]));
  let total = 0;
  let answered = 0;
  let n1Total = 0;
  let n1Answered = 0;

  for (const section of LP_HEARING_TEMPLATE.sections) {
    for (const question of section.questions) {
      total++;
      const value = responseMap.get(question.id);
      const hasValue = value && (!Array.isArray(value) || value.length > 0);
      
      if (hasValue) answered++;
      
      if (question.n1Related) {
        n1Total++;
        if (hasValue) n1Answered++;
      }
    }
  }

  return {
    total,
    answered,
    percentage: Math.round((answered / total) * 100),
    n1Percentage: n1Total > 0 ? Math.round((n1Answered / n1Total) * 100) : 0,
  };
}
