"use client";

/**
 * 提案書自動生成ページ
 */

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Loader2,
  FileText,
  Download,
  Copy,
  Sparkles,
  FileCheck,
} from "lucide-react";

type ProposalTemplate = "simple" | "detailed" | "presentation";

interface ProposalSection {
  id: string;
  title: string;
  content: string;
  order: number;
}

interface GeneratedProposal {
  id: string;
  metadata: {
    projectName: string;
    createdAt: string;
    template: ProposalTemplate;
    pageCount: number;
    wordCount: number;
  };
  sections: ProposalSection[];
  rawMarkdown: string;
  htmlContent: string;
}

const TEMPLATE_DESCRIPTIONS: Record<ProposalTemplate, { name: string; desc: string }> = {
  simple: { name: "シンプル", desc: "5項目の簡潔な提案書" },
  detailed: { name: "詳細", desc: "10項目の詳細な分析レポート" },
  presentation: { name: "プレゼン", desc: "スライド形式の提案資料" },
};

export default function ProposalGeneratorPage() {
  const [researchJson, setResearchJson] = useState("");
  const [template, setTemplate] = useState<ProposalTemplate>("simple");
  const [isLoading, setIsLoading] = useState(false);
  const [proposal, setProposal] = useState<GeneratedProposal | null>(null);
  const [error, setError] = useState<string | null>(null);

  const generateProposal = async () => {
    if (!researchJson.trim()) return;

    setIsLoading(true);
    setError(null);
    setProposal(null);

    try {
      const research = JSON.parse(researchJson);

      const response = await fetch("/api/proposal", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ research, template }),
      });

      const data = await response.json();

      if (data.success) {
        setProposal(data.proposal);
      } else {
        setError(data.error || "生成に失敗しました");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "JSONパース失敗");
    } finally {
      setIsLoading(false);
    }
  };

  const downloadMarkdown = () => {
    if (!proposal) return;
    const blob = new Blob([proposal.rawMarkdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `proposal-${proposal.metadata.projectName}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadHtml = () => {
    if (!proposal) return;
    const fullHtml = `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>${proposal.metadata.projectName} - 提案書</title>
  <style>
    body { font-family: 'Hiragino Sans', sans-serif; line-height: 1.8; max-width: 800px; margin: 0 auto; padding: 40px; }
    h1 { font-size: 24px; border-bottom: 2px solid #333; padding-bottom: 10px; }
    h2 { font-size: 20px; margin-top: 30px; color: #444; }
    h3 { font-size: 16px; color: #666; }
    table { border-collapse: collapse; width: 100%; margin: 15px 0; }
    th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
    th { background: #f5f5f5; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }
  </style>
</head>
<body>
${proposal.htmlContent}
<div class="footer">Generated by LP Builder Pro</div>
</body>
</html>`;
    const blob = new Blob([fullHtml], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `proposal-${proposal.metadata.projectName}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = () => {
    if (!proposal) return;
    navigator.clipboard.writeText(proposal.rawMarkdown);
  };

  return (
    <div className="container mx-auto py-8 px-4 max-w-6xl">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">提案書自動生成</h1>
        <p className="text-muted-foreground">
          リサーチデータから提案書を自動生成します
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* 入力エリア */}
        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>リサーチデータ</CardTitle>
              <CardDescription>
                リサーチ結果のJSONを貼り付けてください
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <Textarea
                value={researchJson}
                onChange={(e) => setResearchJson(e.target.value)}
                placeholder='{\n  "context": {\n    "projectName": "プロジェクト名",\n    "genre": "ジャンル",\n    ...\n  }\n}'
                rows={12}
                className="font-mono text-sm"
              />

              <div>
                <label className="text-sm font-medium">テンプレート</label>
                <Select
                  value={template}
                  onValueChange={(v) => setTemplate(v as ProposalTemplate)}
                >
                  <SelectTrigger className="mt-1">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {Object.entries(TEMPLATE_DESCRIPTIONS).map(([key, { name, desc }]) => (
                      <SelectItem key={key} value={key}>
                        <div>
                          <div className="font-medium">{name}</div>
                          <div className="text-xs text-muted-foreground">{desc}</div>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <Button
                onClick={generateProposal}
                disabled={isLoading || !researchJson.trim()}
                className="w-full"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    生成中...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 mr-2" />
                    提案書を生成
                  </>
                )}
              </Button>

              {error && (
                <div className="p-3 bg-red-50 text-red-600 rounded-lg text-sm">
                  {error}
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* 結果エリア */}
        <div className="space-y-4">
          {proposal ? (
            <>
              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="flex items-center gap-2">
                    <FileCheck className="w-5 h-5 text-green-500" />
                    生成完了
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2 mb-4">
                    <Badge variant="secondary">
                      {proposal.metadata.pageCount}ページ
                    </Badge>
                    <Badge variant="secondary">
                      {proposal.metadata.wordCount.toLocaleString()}文字
                    </Badge>
                    <Badge variant="secondary">
                      {proposal.sections.length}セクション
                    </Badge>
                  </div>

                  <div className="flex gap-2">
                    <Button onClick={downloadMarkdown} variant="outline" className="flex-1">
                      <Download className="w-4 h-4 mr-2" />
                      Markdown
                    </Button>
                    <Button onClick={downloadHtml} variant="outline" className="flex-1">
                      <Download className="w-4 h-4 mr-2" />
                      HTML
                    </Button>
                    <Button onClick={copyToClipboard} variant="outline">
                      <Copy className="w-4 h-4" />
                    </Button>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="text-base">セクション一覧</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    {proposal.sections.map((section) => (
                      <div
                        key={section.id}
                        className="flex items-center gap-2 p-2 bg-gray-50 rounded"
                      >
                        <Badge variant="outline" className="w-6 h-6 justify-center">
                          {section.order}
                        </Badge>
                        <span className="text-sm">{section.title}</span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="text-base">プレビュー</CardTitle>
                </CardHeader>
                <CardContent>
                  <div
                    className="prose prose-sm max-w-none"
                    dangerouslySetInnerHTML={{ __html: proposal.htmlContent }}
                  />
                </CardContent>
              </Card>
            </>
          ) : (
            <Card className="border-dashed">
              <CardContent className="py-12 text-center">
                <FileText className="w-12 h-12 mx-auto text-muted-foreground/30 mb-4" />
                <p className="text-muted-foreground">
                  リサーチデータを入力して「提案書を生成」をクリックしてください
                </p>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}
